# Generated by Django 3.2.6 on 2021-08-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210828_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbnTen', models.CharField(blank=True, max_length=10)),
                ('isbnThirteen', models.CharField(blank=True, max_length=13)),
            ],
        ),
    ]
